version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - nginx
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
